using System;
using System.Collections.Generic;
using System.Linq;
using System.Text;
using System.Threading.Tasks;

namespace Abjad.Code
{
    static class MapTable
    {
        public static Dictionary<char, int> MapScore { get; set; } = new Dictionary<char, int>()
        {
#if (DEBUG || Release)
            {'a',1},
            {'u',21},
            {'b',2},
            {'v',22},
            {'h',8},
            {'t',20},
            {'g',7},
            {'s',19},
            {'i',9},
            {'m',13},
            {'j',10},
            {'n',14},
            {'p',17},
            {'l',12},
            {'o',15},
            {'k',11},
            {'q',17},
            {'e',5},
            {'r',18},
            {'f',6},
            {'x',24},
            {'d',4},
            {'w',23},
            {'c',3},
            {'y',25},
            {'z',26},
#elif (ReleaseFarsi)
            {'ق',19},
            {'س',15},
            {'ر',20},
            {'ع',16},
            {'ت',22},
            {'ی',10},
            {'ش',21},
            {'ط',9},
            {'ظ',27},
            {'ز',7},
            {'غ',28},
            {'ح',8},
            {'چ',30},
            {'ب',2},
            {'پ',29},
            {'ا',1},
            {'ج',3},
            {'ژ',31},
            {'د',4},
            {'گ',32},
            {'و',6},
            {'ض',26},
            {'ه',5},
            {'ذ',25},
            {'ک',11},
            {'ث',23},
            {'ل',12},
            {'خ',24},
            {'ن',14},
            {'ص',18},
            {'م',13},
            {'ف',17},
#endif
        };

        public static Dictionary<char, Rows> MapRow1 { get; set; } = new Dictionary<char, Rows>()
        {
            {'ق',new Rows('ق','ج','ف')},
            {'س',new Rows('س','ژ','م')},
            {'ر',new Rows('ر','د','ص')},
            {'ع',new Rows('ع','گ','ن')},
            {'ت',new Rows('ت','و','خ')},
            {'ی',new Rows('ی','ض','ل')},
            {'ش',new Rows('ش','ه','ث')},
            {'ط',new Rows('ط','ذ','ک')},
            {'ظ',new Rows('ظ','ک','ذ')},
            {'ز',new Rows('ز','ث','ه')},
            {'غ',new Rows('غ','ل','ض')},
            {'ح',new Rows('ح','خ','و')},
            {'چ',new Rows('چ','ن','گ')},
            {'ب',new Rows('ب','ص','د')},
            {'پ',new Rows('پ','م','ژ')},
            {'ا',new Rows('ا','ف','ج')},
            {'ج',new Rows('ج','ق','ا')},
            {'ژ',new Rows('ژ','س','پ')},
            {'د',new Rows('د','ر','ب')},
            {'گ',new Rows('گ','ع','چ')},
            {'و',new Rows('و','ت','ح')},
            {'ض',new Rows('ض','ی','غ')},
            {'ه',new Rows('ه','ش','ز')},
            {'ذ',new Rows('ذ','ط','ظ')},
            {'ک',new Rows('ک','ظ','ط')},
            {'ث',new Rows('ث','ز','ش')},
            {'ل',new Rows('ل','غ','ی')},
            {'خ',new Rows('خ','ح','ت')},
            {'ن',new Rows('ن','چ','ع')},
            {'ص',new Rows('ص','ب','ر')},
            {'م',new Rows('م','پ','س')},
            {'ف',new Rows('ف','ا','ق')},
        };
        public static Dictionary<char, Rows> MapRow2 { get; set; } = new Dictionary<char, Rows>()
        {
            {'ق',new Rows('ق','ج','ف')},
            {'س',new Rows('س','ژ','م')},
            {'ر',new Rows('ر','د','ص')},
            {'ع',new Rows('ع','گ','ن')},
            {'ت',new Rows('ت','و','خ')},
            {'ی',new Rows('ی','ض','ل')},
            {'ش',new Rows('ش','ه','ث')},
            {'ط',new Rows('ط','ذ','ک')},
            {'ظ',new Rows('ظ','ک','ذ')},
            {'ز',new Rows('ز','ث','ه')},
            {'غ',new Rows('غ','ل','ض')},
            {'ح',new Rows('ح','خ','و')},
            {'چ',new Rows('چ','ن','گ')},
            {'ب',new Rows('ب','ص','د')},
            {'پ',new Rows('پ','م','ژ')},
            {'ا',new Rows('ا','ف','ج')},
            {'ج',new Rows('ج','ق','ا')},
            {'ژ',new Rows('ژ','س','پ')},
            {'د',new Rows('د','ر','ب')},
            {'گ',new Rows('گ','ع','چ')},
            {'و',new Rows('و','ت','ح')},
            {'ض',new Rows('ض','ی','غ')},
            {'ه',new Rows('ه','ش','ز')},
            {'ذ',new Rows('ذ','ط','ظ')},
            {'ک',new Rows('ک','ظ','ط')},
            {'ث',new Rows('ث','ز','ش')},
            {'ل',new Rows('ل','غ','ی')},
            {'خ',new Rows('خ','ح','ت')},
            {'ن',new Rows('ن','چ','ع')},
            {'ص',new Rows('ص','ب','ر')},
            {'م',new Rows('م','پ','س')},
            {'ف',new Rows('ف','ا','ق')},
        };
        public static Dictionary<char, Rows> MapRow3 { get; set; } = new Dictionary<char, Rows>()
        {
            {'ق',new Rows('ق','ج','ف')},
            {'س',new Rows('س','ژ','م')},
            {'ر',new Rows('ر','د','ص')},
            {'ع',new Rows('ع','گ','ن')},
            {'ت',new Rows('ت','و','خ')},
            {'ی',new Rows('ی','ض','ل')},
            {'ش',new Rows('ش','ه','ث')},
            {'ط',new Rows('ط','ذ','ک')},
            {'ظ',new Rows('ظ','ک','ذ')},
            {'ز',new Rows('ز','ث','ه')},
            {'غ',new Rows('غ','ل','ض')},
            {'ح',new Rows('ح','خ','و')},
            {'چ',new Rows('چ','ن','گ')},
            {'ب',new Rows('ب','ص','د')},
            {'پ',new Rows('پ','م','ژ')},
            {'ا',new Rows('ا','ف','ج')},
            {'ج',new Rows('ج','ق','ا')},
            {'ژ',new Rows('ژ','س','پ')},
            {'د',new Rows('د','ر','ب')},
            {'گ',new Rows('گ','ع','چ')},
            {'و',new Rows('و','ت','ح')},
            {'ض',new Rows('ض','ی','غ')},
            {'ه',new Rows('ه','ش','ز')},
            {'ذ',new Rows('ذ','ط','ظ')},
            {'ک',new Rows('ک','ظ','ط')},
            {'ث',new Rows('ث','ز','ش')},
            {'ل',new Rows('ل','غ','ی')},
            {'خ',new Rows('خ','ح','ت')},
            {'ن',new Rows('ن','چ','ع')},
            {'ص',new Rows('ص','ب','ر')},
            {'م',new Rows('م','پ','س')},
            {'ف',new Rows('ف','ا','ق')},
        };

    }
}
